import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from '../dist/server/index.js';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(query){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(query).get(...args)||null},async all(){return{results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return{meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}}},async batch(s){sql.exec('BEGIN');try{const r=await Promise.all(s.map(x=>x.run()));sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
const files=new Map();const BUCKET={async put(k,b){files.set(k,new Uint8Array(b))},async get(k){const b=files.get(k);return b?{body:new Blob([b]).stream(),size:b.length}:null},async delete(k){files.delete(k)}};
const env={DB,BUCKET,FGDLL_ADMIN_EMAILS:'admin@example.com',ASSETS:{fetch:async()=>new Response('',{status:404})}};
async function req(path,method='GET',body=null,user='',origin='http://localhost'){const headers={};if(user)headers['oai-authenticated-user-email']=user;if(method!=='GET')headers.origin=origin;if(body&&!(body instanceof FormData)){headers['content-type']='application/json';body=JSON.stringify(body)}return worker.fetch(new Request('http://localhost'+path,{method,headers,body}),env,{waitUntil(){},passThroughOnException(){}})}
let r=await req('/api/brand');assert.equal(r.status,200);let items=(await r.json()).resources;assert.equal(items.length,10);assert.equal(items.filter(x=>x.kind==='logo').length,9);console.log('Public catalog: nine logos and Ringbearer');
for(const method of ['POST','DELETE']){assert.equal((await req('/api/brand',method,{})).status,401);assert.equal((await req('/api/brand',method,{},'someone@example.com')).status,403)}
assert.equal((await req('/api/brand','POST',{},'admin@example.com','http://evil.example')).status,403);console.log('Unauthorized and cross-origin writes blocked');
const form=()=>{const f=new FormData();f.set('name','Logo prueba');f.set('kind','logo');f.set('file',new File([readFileSync('public/marca/logo-1.png')],'logo.png',{type:'image/png'}));return f};
r=await req('/api/brand','POST',form(),'admin@example.com');assert.equal(r.status,200,await r.clone().text());const {id}=await r.json();assert.equal(files.size,1);
r=await req('/api/brand/file?id='+id);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await r.arrayBuffer()),readFileSync('public/marca/logo-1.png'));
const edit=new FormData();edit.set('id',id);edit.set('revision','1');edit.set('name','Nuevo nombre');r=await req('/api/brand','POST',edit,'admin@example.com');assert.equal(r.status,200);assert.equal((await req('/api/brand','POST',edit,'admin@example.com')).status,409);
const replacement=form();replacement.set('id',id);replacement.set('revision','2');replacement.set('name','Reemplazado');assert.equal((await req('/api/brand','POST',replacement,'admin@example.com')).status,200);assert.equal(files.size,1);
assert.equal((await req('/api/brand','DELETE',{id,revision:3,confirmation:'Reemplazado'},'admin@example.com')).status,200);assert.equal(files.size,0);assert.equal((await req('/api/brand/file?id='+id)).status,404);console.log('Upload, byte retrieval, rename, conflict, replace and delete passed');
assert.equal((await req('/api/brand','DELETE',{id:'brand-logo-1',revision:1,confirmation:'Zona Tiburón'},'admin@example.com')).status,200);items=(await (await req('/api/brand')).json()).resources;assert.ok(!items.some(x=>x.id==='brand-logo-1'));assert.equal((await req('/api/brand/file?id=brand-logo-1')).status,404);console.log('Bundled logo deletion persists');
const bad=form();bad.set('file',new File(['<html>bad</html>'],'logo.png'));assert.equal((await req('/api/brand','POST',bad,'admin@example.com')).status,400);
const opaque=new FormData();opaque.set('name','Logo con fondo');opaque.set('kind','logo');opaque.set('file',new File([Uint8Array.of(137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,2,0,0,0,0,0,0,0)],'opaque.png',{type:'image/png'}));r=await req('/api/brand','POST',opaque,'admin@example.com');assert.equal(r.status,400);assert.match(await r.text(),/sin fondo/);
const font=new FormData();font.set('name','Ringbearer prueba');font.set('kind','font');font.set('file',new File([readFileSync('public/marca/ringbearer.ttf')],'ringbearer.ttf'));r=await req('/api/brand','POST',font,'admin@example.com');assert.equal(r.status,200);console.log('Font upload and invalid-file validation passed');
const preset=new FormData();preset.set('name','Texto institucional');preset.set('kind','text');preset.set('text','GUERREROS DE LA LUZ');r=await req('/api/brand','POST',preset,'admin@example.com');assert.equal(r.status,200,await r.clone().text());const presetId=(await r.json()).id;items=(await (await req('/api/brand')).json()).resources;const textItem=items.find(x=>x.id===presetId);assert.equal(textItem.kind,'text');assert.equal(textItem.content,'GUERREROS DE LA LUZ');assert.equal((await req('/api/brand/file?id='+presetId)).status,404);console.log('Reusable text preset creation and catalog rendering passed');
const adminPage=await req('/administracion/marca');const authHtml=await adminPage.text();assert.equal(adminPage.status,302);assert.equal(new URL(adminPage.headers.get('location')).pathname,'/signin-with-chatgpt');assert.ok(!authHtml.includes('id="resource-form"'));r=await req('/herramientas/marca-imagenes');assert.equal(r.status,200);const html=await r.text();assert.ok(html.includes('Agrega texto'));console.log('Editor rendering and admin sign-in protection passed');
