"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { SubFooter, SubHeader } from "../section-shell";

type Tab = "registration" | "centers" | "certificate";
type ContentRow = Record<string, string | number>;
type UniversityContent = { programs: ContentRow[]; modules: ContentRow[]; materials: ContentRow[]; settings: Record<string, string> };
type PortalMessage = { kind: "ok" | "error"; text: string; accessGranted?: boolean };
const versions = [
  { value: "2022", label: "Versión 2022", note: "Básico obligatorio", text: "La base formativa que todo participante debe completar." },
  { value: "2025", label: "Versión 2025", note: "Actualización", text: "Recorrido de liderazgo correspondiente a la generación 2025." },
  { value: "2026", label: "Versión 2026", note: "Generación actual", text: "Formación vigente para quienes cursan el diplomado este año." },
];
const resourceTypeLabels: Record<string, string> = {
  digital_workbook: "Cuadernillo digital", workbook_pdf: "Cuadernillo PDF", anthology_pdf: "Antología PDF",
  material: "Material", guide: "Guía", assignment: "Entrega de tareas", form: "Formulario", document: "Documento",
};

async function send(url: string, form: HTMLFormElement) {
  const body = Object.fromEntries(new FormData(form).entries());
  const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || "No fue posible completar el registro.");
  return data as Record<string, unknown>;
}

export function UniversityPortal() {
  const [tab, setTab] = useState<Tab>("registration");
  const [version, setVersion] = useState("2022");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<PortalMessage | null>(null);
  const [content, setContent] = useState<UniversityContent>({ programs: [], modules: [], materials: [], settings: {} });
  useEffect(() => { fetch("/api/university/content", { cache: "no-store" }).then((response) => response.ok ? response.json() : Promise.reject()).then(setContent).catch(() => undefined); }, []);
  const versionOptions = [...versions, ...content.programs
    .map((program) => String(program.generation || "").trim())
    .filter((generation, index, all) => generation && !versions.some((item) => item.value === generation) && all.indexOf(generation) === index)
    .map((generation) => ({ value: generation, label: `Versión ${generation}`, note: "Programa disponible", text: "Materiales y recursos publicados por Universidad FGDLL." }))];
  const universityPhone = content.settings.phone || "9999011852";
  const displayedPhone = universityPhone.replace(/(\d{3})(\d{3})(\d{4})/, "$1 $2 $3");

  async function submit(event: FormEvent<HTMLFormElement>, url: string, success: (data: Record<string, unknown>) => string, grantsAccess = false) {
    event.preventDefault(); const form = event.currentTarget; setBusy(true); setMessage(null);
    try { const data = await send(url, form); setMessage({ kind: "ok", text: success(data), accessGranted: grantsAccess || data.accessGranted === true }); form.reset(); }
    catch (error) { setMessage({ kind: "error", text: error instanceof Error ? error.message : "No fue posible completar el registro." }); }
    finally { setBusy(false); }
  }

  return <><SubHeader label="Universidad FGDLL" /><main className="unified-university">
    <section className="uni-hero"><div className="shell uni-hero-grid"><div><span className="eyebrow light">Universidad FGDLL · Formación para el servicio</span><h1>Tu formación comienza <em>contigo.</em></h1><p>Inscríbete, continúa tu diplomado y solicita tu reconocimiento sin salir del portal institucional.</p><div className="hero-actions"><a className="button button-gold" href="#registro">Entrar a Universidad →</a><Link className="button button-ghost" href="/universidad/dpl1-2022">Ver Diplomado 2022</Link><Link className="button button-ghost" href="/administracion/universidad">Panel administrativo</Link></div></div><aside><img src="/logo-gdll.png" alt="Escudo de Guerreros de la Luz" /><small>CONTACTO UNIVERSIDAD</small><a href={`https://wa.me/52${universityPhone}?text=Hola%2C%20quiero%20informaci%C3%B3n%20sobre%20Universidad%20FGDLL`}>WhatsApp · {displayedPhone}</a><a href={`tel:+52${universityPhone}`}>Llamar · {displayedPhone}</a></aside></div></section>
    <section className="section uni-portal" id="registro"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow">Registro institucional</span><h2>Elige lo que necesitas.</h2></div><p>Tu registro queda guardado para seguimiento y el acceso al aula se abre de inmediato, sin esperar aprobación.</p></div><div className="uni-tabs" role="tablist"><button className={tab === "registration" ? "active" : ""} onClick={() => { setTab("registration"); setMessage(null); }}>Inscripción</button><button className={tab === "centers" ? "active" : ""} onClick={() => { setTab("centers"); setMessage(null); }}>Directores de centros</button><button className={tab === "certificate" ? "active" : ""} onClick={() => { setTab("certificate"); setMessage(null); }}>Reconocimiento</button></div>
      {message && <div className={`uni-message ${message.kind}`}><span>{message.text}</span>{message.accessGranted && <a className="button button-gold" href="#aula">Entrar al aula completa →</a>}</div>}
      {tab === "registration" && <div className="uni-workspace"><div><h3>Selecciona tu generación</h3><div className="uni-open-access"><strong>Acceso inmediato</strong><p>Al enviar tu registro podrás consultar los videos y materiales publicados de todas las generaciones disponibles.</p></div><div className="uni-version-grid">{versionOptions.map((item) => <button type="button" key={item.value} className={version === item.value ? "active" : ""} onClick={() => setVersion(item.value)}><b>{item.label}</b><span>{item.note}</span><p>{item.text}</p></button>)}</div></div><form className="report-form" onSubmit={(event) => submit(event, "/api/university/registrations", () => "Tu registro quedó guardado y tu acceso ya está activo. Puedes entrar ahora mismo a todos los videos y materiales de Universidad FGDLL.", true)}><input type="hidden" name="diplomaVersion" value={version} /><label>Nombre completo<input name="fullName" required maxLength={180} /></label><label>Correo electrónico<input name="email" type="email" required maxLength={254} /></label><label>Número de celular<input name="mobilePhone" type="tel" required inputMode="tel" /></label><label>Grupo o centro<input name="organization" required maxLength={180} /></label><label>Tipo de participante<select name="participantType" defaultValue="participant"><option value="participant">Participante</option><option value="center_director">Director de centro</option></select></label><label>Notas sobre tu situación en el diplomado (opcional)<textarea name="requestNotes" rows={4} maxLength={2000} placeholder="Cuéntanos si ya comenzaste, qué módulos cursaste, si necesitas retomar o cualquier situación que debamos considerar." /></label><button className="button button-gold" disabled={busy}>{busy ? "Guardando…" : `Registrarme y entrar · ${version}`}</button></form></div>}
      {tab === "centers" && <div className="uni-workspace single-info"><div><span className="eyebrow">Registro colectivo</span><h3>Inscribe a los participantes de tu centro.</h3><p>Escribe un nombre completo por línea. La relación quedará guardada para seguimiento y el aula se abrirá de inmediato.</p></div><form className="report-form" onSubmit={(event) => submit(event, "/api/university/center-batches", (data) => `Relación guardada con el folio ${data.id}. Participantes registrados: ${data.participantCount}. Ya pueden consultar el aula completa.`, true)}><label>Correo del director<input name="directorEmail" type="email" required /></label><label>Número de contacto<input name="mobilePhone" type="tel" required /></label><label>Nombre del centro<input name="centerName" required /></label><label>Generación<select name="diplomaVersion" defaultValue="2026">{versionOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Participantes, uno por línea<textarea name="participantNames" rows={8} required /></label><label>Notas sobre la situación del centro o participantes (opcional)<textarea name="requestNotes" rows={4} maxLength={2000} placeholder="Aclara avances, pagos, participantes que retomarán o cualquier dato útil para dar seguimiento." /></label><button className="button button-gold" disabled={busy}>{busy ? "Guardando…" : "Guardar relación y entrar"}</button></form></div>}
      {tab === "certificate" && <div className="uni-workspace single-info"><div><span className="eyebrow">Solicitud de reconocimiento</span><h3>Primero validamos tu registro.</h3><p>La impresión o reimpresión tiene un costo aproximado de <strong>{content.settings.recognitionCost || "$50 a $100"} MXN</strong>, según el caso. Nos comunicaremos contigo para confirmar la información, el costo final y la entrega.</p><div className="uni-spin-card"><span>TRANSFERENCIA SPIN</span><strong>{content.settings.spinHolder || "LAURA CORTAZAR"}</strong><p>CLABE: {content.settings.spinClabe || "728969000008838228"}</p><p>Código de depósito: {content.settings.spinDepositCode || "2242-1787-4421-1658"}</p></div></div><form className="report-form" onSubmit={(event) => submit(event, "/api/university/certificates", (data) => `Solicitud registrada con el folio ${data.id}. Nos comunicaremos contigo para validarla.`)}><label>Nombre completo<input name="fullName" required /></label><label>Número de contacto<input name="mobilePhone" type="tel" required /></label><label>Grupo o centro<input name="groupName" required /></label><label>Generación<select name="diplomaVersion" defaultValue="2022">{versionOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Pago del diplomado<select name="paymentStatus" defaultValue="total"><option value="total">Pago total realizado</option><option value="partial">Pago parcial realizado</option><option value="pending">Pago pendiente</option></select></label><label>Tipo de solicitud<select name="requestType" defaultValue="printing"><option value="printing">Primera impresión</option><option value="reprinting">Reimpresión</option></select></label><label>Notas para validar tu reconocimiento (opcional)<textarea name="requestNotes" rows={4} maxLength={2000} placeholder="Especifica módulos concluidos, fecha aproximada, pagos o cualquier situación que debamos revisar." /></label><button className="button button-gold" disabled={busy}>{busy ? "Registrando…" : "Solicitar reconocimiento"}</button></form></div>}
    </div></section>
    <section className="section uni-learning" id="aula"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow light">Aula abierta · Universidad FGDLL</span><h2>Comprender. Reflexionar. Expresar.</h2></div><p>Quienes envían su registro pueden consultar todos los videos, cuadernillos y materiales publicados, sin esperar admisión manual.</p></div><div className="uni-route"><article><b>01</b><h3>Mira la clase</h3><p>Escucha el módulo completo y reconoce las ideas esenciales.</p></article><article><b>02</b><h3>Comprende</h3><p>Relaciona el contenido con tu experiencia y tu servicio.</p></article><article><b>03</b><h3>Escribe</h3><p>Realiza cuatro cuartillas a mano, con tus propias palabras.</p></article><article><b>04</b><h3>Entrega</h3><p>Envía fotografías claras, completas y en el orden correcto.</p></article></div><div className="uni-course-action"><div><span>GENERACIÓN 2026 · NUEVO</span><h3>Seis módulos con videos y cuadernillos interactivos</h3></div><a className="button button-gold" href="/universidad/dpl-2026/index.html">Entrar al DPL-2026 →</a></div><div className="uni-course-action"><div><span>GENERACIÓN 2022</span><h3>Trece módulos disponibles</h3></div><Link className="button button-gold" href="/universidad/dpl1-2022">Entrar al diplomado →</Link></div></div></section>
    {content.settings.taskUrl && <section className="uni-delivery-strip"><div className="shell"><div><span>ENTREGA DE ACTIVIDADES</span><h3>Envía tus tareas desde el enlace vigente.</h3></div><a className="button button-gold" href={content.settings.taskUrl} target="_blank" rel="noopener noreferrer">Subir mis tareas →</a></div></section>}
    {content.programs.length > 0 && <section className="section uni-catalog"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow">Programas y recursos</span><h2>Tu aula digital.</h2></div><p>Los contenidos que publique Administración aparecerán aquí automáticamente.</p></div>{content.programs.map((program) => { const modules = content.modules.filter((item) => item.program_id === program.id); const materials = content.materials.filter((item) => item.program_id === program.id || !item.program_id); return <article className="uni-program-block" key={program.id}><header><div><span>GENERACIÓN {program.generation}</span><h3>{program.title}</h3><p>{program.description}</p></div><b>{modules.length} módulos</b></header>{modules.length > 0 && <div className="uni-module-links">{modules.map((item, index) => <a href={String(item.video_url)} target="_blank" rel="noopener noreferrer" key={item.id}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item.title}</strong><b>Ver video ↗</b></a>)}</div>}{materials.length > 0 && <div className="uni-material-links">{materials.map((item) => <a href={String(item.resource_url)} target={String(item.resource_url).startsWith("/") ? undefined : "_blank"} rel="noopener noreferrer" key={item.id}><small>{resourceTypeLabels[String(item.resource_type)] || item.resource_type}</small><strong>{item.title}</strong><p>{item.description}</p></a>)}</div>}</article>; })}</div></section>}
  </main><SubFooter /></>;
}
