import Link from "next/link";
import { SubFooter, SubHeader } from "../section-shell";

const tools = [
  { n: "01", title: "Mi servicio", text: "Responsabilidades, compromisos y prioridades del líder.", tag: "Punto de partida" },
  { n: "02", title: "Materiales para líderes", text: "Responsivas, formatos y documentos listos para consultar o imprimir.", tag: "Operación", href: "#materiales" },
  { n: "03", title: "Universidad FGDLL", text: "Diplomados y materiales separados por generación.", tag: "Formación", href: "/universidad" },
  { n: "04", title: "Biblioteca de Testimonios", text: "157 temas con fuentes y preguntas para ordenar la experiencia.", tag: "Recursos", href: "/testimonios" },
  { n: "05", title: "Red nacional", text: "Directorio, zonas, responsables y coordinación.", tag: "Comunidad", href: "/#directorio" },
  { n: "06", title: "Ética e Integridad", text: "Orientación, límites y canal de reporte responsable.", tag: "Cuidado", href: "/etica" },
];

export default function PortalPage() {
  return <><SubHeader label="Portal interno" /><main className="subpage">
    <section className="subhero portal-subhero"><div className="shell subhero-grid"><div><span className="eyebrow light">Tablero de liderazgo</span><h1>Servir con orden.<br /><em>Actuar con claridad.</em></h1><p>Una ruta institucional para consultar lo esencial, preparar el servicio y encontrar el recurso correcto sin perderse entre mensajes.</p></div><div className="quick-panel"><span>ACCESO RÁPIDO</span><a href="#materiales"><b>Materiales para líderes</b><i>↓</i></a><Link href="/universidad"><b>Universidad FGDLL</b><i>→</i></Link><Link href="/#calendario"><b>Calendario 2026</b><i>→</i></Link><Link href="/etica"><b>Ética e Integridad</b><i>→</i></Link></div></div></section>
    <section className="section portal-tools"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow">Ruta de servicio</span><h2>Lo que cada líder necesita.</h2></div><p>El portal está organizado por intención de uso: saber qué hacer, encontrar cómo hacerlo y dar seguimiento con responsabilidad.</p></div><div className="tool-catalog">{tools.map((tool) => <article key={tool.n}><span>{tool.n}</span><small>{tool.tag}</small><h3>{tool.title}</h3><p>{tool.text}</p>{tool.href ? <Link href={tool.href}>Abrir sección →</Link> : <button disabled>Próxima conexión</button>}</article>)}</div></div></section>
    <section className="section leader-materials" id="materiales"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow light">Materiales para líderes</span><h2>Documentos para conducir y cuidar.</h2></div><p>Protocolos para coordinar cada sesión y responsivas para proteger a quienes participan. Consulta siempre el documento completo antes de usarlo.</p></div>
    <div className="material-group-heading"><div><span>01</span><h3>Protocolos de sesión</h3></div><p>Guías de lectura y coordinación para mantener orden, tiempos y unidad.</p></div><div className="material-grid">
      <article className="material-card"><div className="material-preview"><img src="/materiales/protocolo-sesion-diaria.png" alt="Vista previa del Protocolo de Sesión Diaria de FGDLL" /></div><div className="material-content"><div className="material-meta"><span>Operación de grupo</span><small>PDF · 3 páginas · A4</small></div><h3>Protocolo de Sesión Diaria</h3><p>Guía para abrir, conducir y cerrar la sesión. Incluye bienvenida, enunciado, tribuna, séptima tradición, despedida y anexos de apoyo.</p><div className="material-actions"><a className="button button-gold" href="/materiales/protocolo-sesion-diaria.pdf" target="_blank" rel="noreferrer">Ver documento</a><a className="button button-ghost" href="/materiales/protocolo-sesion-diaria.pdf" download>Descargar PDF</a></div></div></article>
      <article className="material-card"><div className="material-preview"><img src="/materiales/protocolo-aniversarios.png" alt="Vista previa del Protocolo de Aniversarios de FGDLL" /></div><div className="material-content"><div className="material-meta"><span>Sesión especial</span><small>PDF · 3 páginas · A4</small></div><h3>Protocolo de Aniversarios</h3><p>Orden operativo para las sesiones de aniversario: duración, participantes, tiempos de tribuna, séptima tradición, reconocimientos y cierre.</p><div className="material-actions"><a className="button button-gold" href="/materiales/protocolo-aniversarios.pdf" target="_blank" rel="noreferrer">Ver documento</a><a className="button button-ghost" href="/materiales/protocolo-aniversarios.pdf" download>Descargar PDF</a></div></div></article>
    </div>
    <div className="material-group-heading"><div><span>02</span><h3>Responsivas y consentimiento</h3></div><p>Formatos para informar, documentar y resguardar la participación responsable.</p></div><div className="material-grid">
      <article className="material-card"><div className="material-preview"><img src="/materiales/responsiva-completa-2026.png" alt="Vista previa de la hoja responsiva completa FGDLL 2026" /></div><div className="material-content"><div className="material-meta"><span>Recomendada</span><small>PDF · 2 páginas · Carta</small></div><h3>Hoja Responsiva FGDLL 2026</h3><p>Versión completa de consentimiento informado para la Experiencia de Hacienda. Incluye datos de salud, confidencialidad, derechos, riesgos y firmas.</p><div className="material-actions"><a className="button button-gold" href="/materiales/hoja-responsiva-fgdll-2026-completa.pdf" target="_blank" rel="noreferrer">Ver documento</a><a className="button button-ghost" href="/materiales/hoja-responsiva-fgdll-2026-completa.pdf" download>Descargar PDF</a></div></div></article>
      <article className="material-card"><div className="material-preview"><img src="/materiales/responsiva-compacta-2026.png" alt="Vista previa de la hoja responsiva compacta FGDLL 2026" /></div><div className="material-content"><div className="material-meta"><span>Versión compacta</span><small>PDF · 2 páginas · Carta</small></div><h3>Hoja Responsiva FGDLL 2026 · Compacta</h3><p>Formato resumido para impresión rápida. Conserva las ocho cláusulas esenciales, datos del participante, consentimiento y firmas.</p><div className="material-actions"><a className="button button-gold" href="/materiales/hoja-responsiva-fgdll-2026-compacta.pdf" target="_blank" rel="noreferrer">Ver documento</a><a className="button button-ghost" href="/materiales/hoja-responsiva-fgdll-2026-compacta.pdf" download>Descargar PDF</a></div></div></article>
    </div><div className="material-note"><strong>Uso interno FGDLL</strong><span>Antes de cada actividad, el líder debe confirmar que usa la versión vigente del protocolo o formato correspondiente. Las responsivas firmadas deben resguardarse con confidencialidad.</span></div></div></section>
    <section className="section operating"><div className="shell operating-grid"><div><span className="eyebrow light">Centro de Operaciones</span><h2>Una base firme para no improvisar.</h2><p>La operación se agrupa por tipo de necesidad. Así cada responsable puede ubicar protocolos y documentos en el momento correcto.</p></div><div className="operating-list"><article><span>PROTOCOLOS</span><h3>Sesión diaria · Aniversarios · Experiencias</h3><p>Apertura, roles, seguridad, bitácora y cierre responsable.</p></article><article><span>RESPONSIVAS</span><h3>Adultos · Menores · Apoyos</h3><p>Consentimiento, contactos de emergencia y asignación responsable.</p></article><article><span>REGLAMENTOS</span><h3>Grupo · Hacienda · Liderazgo</h3><p>Disciplina, respeto, límites y uso adecuado de los espacios.</p></article></div></div></section>
    <section className="section next-step"><div className="shell"><div><span>PRÓXIMA ETAPA</span><h2>Completar la biblioteca operativa.</h2></div><p>La siguiente incorporación reunirá reglamentos, formatos de seguimiento y documentos de experiencias en esta misma ruta de consulta.</p></div></section>
  </main><SubFooter /></>;
}
