'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,type PointerEvent as PE} from 'react';
import {brandJson,loadBrandFont,type BrandResource} from '../../lib/brand-client';
import './editor.css';
type Picture={el:HTMLImageElement;name:string;width:number;height:number};
type Transform={x:number;y:number;size:number;opacity:number;rotation:number};
type Target='logo'|'logo2'|'text';
const initialLogo2:Transform={x:.22,y:.78,size:.2,opacity:1,rotation:0};
const initialLogo:Transform={x:.78,y:.78,size:.2,opacity:1,rotation:0};
const initialText:Transform={x:.5,y:.88,size:.65,opacity:1,rotation:0};
const positions=['Superior izquierda','Superior centro','Superior derecha','Centro izquierda','Centro','Centro derecha','Inferior izquierda','Inferior centro','Inferior derecha'];
function image(src:string,name:string):Promise<Picture>{return new Promise((resolve,reject)=>{const el=new Image();el.onload=()=>{if(!el.naturalWidth||!el.naturalHeight)reject(new Error('Imagen sin dimensiones válidas.'));else resolve({el,name,width:el.naturalWidth,height:el.naturalHeight})};el.onerror=()=>reject(new Error('No se pudo abrir la imagen.'));el.src=src})}
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n))}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export default function Editor(){
 const [resources,setResources]=useState<BrandResource[]>([]),[catalogLoading,setCatalogLoading]=useState(true),[catalogError,setCatalogError]=useState(''),[admin,setAdmin]=useState(false);
 const [photo,setPhoto]=useState<Picture|null>(null),[logo,setLogo]=useState<Picture|null>(null),[logoId,setLogoId]=useState(''),[showLogo,setShowLogo]=useState(true);
 const [logo2,setLogo2]=useState<Picture|null>(null),[logo2Id,setLogo2Id]=useState(''),[showLogo2,setShowLogo2]=useState(true),[secondEnabled,setSecondEnabled]=useState(false);
 const logo2Request=useRef(0);
 const [text,setText]=useState(''),[color,setColor]=useState('#ffffff'),[fontId,setFontId]=useState(''),[family,setFamily]=useState(''),[fontBusy,setFontBusy]=useState(false),[fontError,setFontError]=useState('');
 const [target,setTarget]=useState<Target>('logo'),[transforms,setTransforms]=useState({logo:initialLogo,logo2:initialLogo2,text:initialText});
 const [format,setFormat]=useState('png'),[quality,setQuality]=useState(.92),[busy,setBusy]=useState(false),[status,setStatus]=useState('Sube una imagen para comenzar.');
 const canvasRef=useRef<HTMLCanvasElement>(null),drag=useRef<{id:number;target:Target;dx:number;dy:number}|null>(null),logoRequest=useRef(0),photoRequest=useRef(0);
 async function chooseLogo(resource:BrandResource,slot:'logo'|'logo2'='logo'){const counter=slot==='logo2'?logo2Request:logoRequest;const n=++counter.current;try{const loaded=await image(resource.url,resource.name);if(n===counter.current){if(slot==='logo2'){setLogo2(loaded);setLogo2Id(resource.id);setShowLogo2(true)}else{setLogo(loaded);setLogoId(resource.id);setShowLogo(true)}setTarget(slot);setStatus('Logotipo seleccionado. Puedes moverlo con el dedo.')}}catch(e){if(n===counter.current)setStatus((e as Error).message)}}
 async function refresh(){setCatalogLoading(true);setCatalogError('');try{const d=await fetch('/api/brand',{cache:'no-store'}).then(brandJson);setResources(d.resources);const first=d.resources.find((r:BrandResource)=>r.id==='brand-logo-8')??d.resources.find((r:BrandResource)=>r.kind==='logo');if(first&&!logo)void chooseLogo(first);const font=d.resources.find((r:BrandResource)=>r.id==='brand-ringbearer')??d.resources.find((r:BrandResource)=>r.kind==='font');if(font&&!fontId)setFontId(font.id);}catch(e){setCatalogError((e as Error).message)}finally{setCatalogLoading(false)}}
 useEffect(()=>{document.title='Logos y texto en imágenes | FGDLL';void refresh();fetch('/api/portal/me',{cache:'no-store'}).then(brandJson).then(d=>setAdmin(d.profile?.role==='admin')).catch(()=>{});},[]);
 const selectedFont=resources.find(r=>r.id===fontId&&r.kind==='font');
 useEffect(()=>{let alive=true;setFamily('');setFontError('');if(!selectedFont){setFontBusy(false);return}setFontBusy(true);loadBrandFont(selectedFont).then(f=>{if(alive)setFamily(f)}).catch(()=>{if(alive)setFontError('No se pudo cargar esta tipografía. Selecciona otra o actualiza la galería.')}).finally(()=>{if(alive)setFontBusy(false)});return()=>{alive=false}},[selectedFont]);
 async function upload(file:File|undefined,kind:'photo'|'logo'|'logo2') {if(!file)return;if(!file.type.startsWith('image/')){setStatus('Selecciona un archivo de imagen.');return}if(kind!=='photo'&&(file.type!=='image/png'||!/\.png$/i.test(file.name))){setStatus('Sube el logotipo como PNG sin fondo.');return}const counter=kind==='photo'?photoRequest:kind==='logo2'?logo2Request:logoRequest;const n=++counter.current;const url=URL.createObjectURL(file);try{const p=await image(url,file.name);if(n!==counter.current)return;if(kind==='photo'){setPhoto(p);setStatus(`${p.width} × ${p.height} px. Imagen lista.`)}else if(kind==='logo2'){setLogo2(p);setLogo2Id('local');setShowLogo2(true);setTarget('logo2')}else{setLogo(p);setLogoId('local');setShowLogo(true);setTarget('logo')}}catch(e){setStatus((e as Error).message)}finally{URL.revokeObjectURL(url)}}
 function textLayout(ctx:CanvasRenderingContext2D){ctx.font=`200px "${family}"`;ctx.textAlign='left';ctx.textBaseline='alphabetic';const lines=text.split('\n').slice(0,6);const metrics=lines.map(line=>ctx.measureText(line||' '));const ascent=Math.max(200,...metrics.map(m=>m.actualBoundingBoxAscent||0)),descent=Math.max(50,...metrics.map(m=>m.actualBoundingBoxDescent||0));const lineHeight=ascent+descent+20;const width=Math.max(1,...metrics.map(m=>Math.max(m.width,m.actualBoundingBoxRight||0)+Math.max(0,m.actualBoundingBoxLeft||0)))+40;return{lines,metrics,width,height:lineHeight*lines.length+40,lineHeight,ascent}}
 function layerDims(which:Target,width:number,ctx:CanvasRenderingContext2D){const t=transforms[which];const w=width*t.size;if(which!=='text'){const pic=which==='logo2'?logo2:logo;return{w,h:pic?w*pic.height/pic.width:w}};const l=textLayout(ctx);return{w,h:w*l.height/l.width}}
 function drawLayer(ctx:CanvasRenderingContext2D,which:Target,width:number,height:number){if(which==='logo'&&(!logo||!showLogo))return;if(which==='logo2'&&(!logo2||!showLogo2||!secondEnabled))return;if(which==='text'&&(!text.trim()||!family||fontBusy))return;const t=transforms[which];const {w,h}=layerDims(which,width,ctx);ctx.save();ctx.translate(t.x*width,t.y*height);ctx.rotate(t.rotation*Math.PI/180);ctx.globalAlpha=t.opacity;if(which!=='text')ctx.drawImage((which==='logo2'?logo2:logo)!.el,-w/2,-h/2,w,h);else{const l=textLayout(ctx);ctx.translate(-w/2,-h/2);ctx.scale(w/l.width,w/l.width);ctx.font=`200px "${family}"`;ctx.fillStyle=color;ctx.textBaseline='alphabetic';l.lines.forEach((line,i)=>{const m=l.metrics[i];const left=Math.max(0,m.actualBoundingBoxLeft||0);ctx.fillText(line,20+left+(l.width-40-m.width-left)/2,20+l.ascent+i*l.lineHeight)})}ctx.restore()}
 function draw(ctx:CanvasRenderingContext2D,w:number,h:number,exporting=false){ctx.clearRect(0,0,w,h);if(!photo)return;if(exporting&&format==='jpeg'){ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h)}ctx.drawImage(photo.el,0,0,w,h);drawLayer(ctx,'logo',w,h);drawLayer(ctx,'logo2',w,h);drawLayer(ctx,'text',w,h)}
 useEffect(()=>{const c=canvasRef.current;if(!c||!photo)return;const s=Math.min(1,1500/Math.max(photo.width,photo.height));c.width=Math.round(photo.width*s);c.height=Math.round(photo.height*s);const ctx=c.getContext('2d');if(ctx)draw(ctx,c.width,c.height)},[photo,logo,showLogo,logo2,showLogo2,secondEnabled,text,color,family,fontBusy,transforms]);
 function update(p:Partial<Transform>){setTransforms(t=>({...t,[target]:{...t[target],...p}}))}
 function point(e:PE<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}}
 function down(e:PE<HTMLCanvasElement>){const c=e.currentTarget,ctx=c.getContext('2d');if(!ctx)return;const p=point(e);for(const which of ['text','logo2','logo'] as Target[]){if(which==='logo'&&(!logo||!showLogo)||which==='logo2'&&(!logo2||!showLogo2||!secondEnabled)||which==='text'&&(!text.trim()||!family))continue;const t=transforms[which],d=layerDims(which,c.width,ctx),angle=-t.rotation*Math.PI/180,dx=p.x-t.x*c.width,dy=p.y-t.y*c.height;const x=dx*Math.cos(angle)-dy*Math.sin(angle),y=dx*Math.sin(angle)+dy*Math.cos(angle);if(Math.abs(x)<=d.w/2+10&&Math.abs(y)<=d.h/2+10){setTarget(which);drag.current={id:e.pointerId,target:which,dx,dy};c.setPointerCapture(e.pointerId);break}}}
 function move(e:PE<HTMLCanvasElement>){const d=drag.current;if(!d||d.id!==e.pointerId)return;const p=point(e),c=e.currentTarget;setTransforms(t=>({...t,[d.target]:{...t[d.target],x:clamp((p.x-d.dx)/c.width,0,1),y:clamp((p.y-d.dy)/c.height,0,1)}}))}
 function quick(i:number){const c=canvasRef.current,ctx=c?.getContext('2d');if(!c||!ctx||!photo)return;const d=layerDims(target,c.width,ctx),a=transforms[target].rotation*Math.PI/180;const mx=Math.min(.5,(Math.abs(d.w*Math.cos(a))+Math.abs(d.h*Math.sin(a)))/2/c.width+.02),my=Math.min(.5,(Math.abs(d.w*Math.sin(a))+Math.abs(d.h*Math.cos(a)))/2/c.height+.02);update({x:[mx,.5,1-mx][i%3],y:[my,.5,1-my][Math.floor(i/3)]})}
 async function exportImage(){if(!photo||fontBusy||(text.trim()&&!family))return;setBusy(true);try{const c=document.createElement('canvas');c.width=photo.width;c.height=photo.height;const ctx=c.getContext('2d');if(!ctx)throw Error();draw(ctx,c.width,c.height,true);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,`image/${format}`,quality));if(!blob)throw Error();const ext=blob.type.split('/')[1]==='jpeg'?'jpg':blob.type.split('/')[1];downloadBlob(blob,`${photo.name.replace(/\.[^.]+$/,'')}-FGDLL.${ext}`);setStatus(`Imagen lista: ${photo.width} × ${photo.height} px.`)}catch{setStatus('No se pudo descargar. Prueba una imagen más pequeña o cambia el formato.')}finally{setBusy(false)}}
 const t=transforms[target];
 return <main className="brand-app"><header className="brand-header"><Link href="/herramientas">← Herramientas FGDLL</Link>{admin&&<Link href="/administracion/marca">Administrar recursos</Link>}</header><div className="brand-container"><h1>Tu imagen, con identidad.</h1><p>Agrega hasta dos logos y texto. Toca un elemento para ajustarlo o arrástralo con el dedo.</p><div className="brand-editor-layout"><section className="brand-workspace"><label className="brand-upload">{photo?'Cambiar imagen':'Subir imagen'}<input type="file" accept="image/*" onChange={e=>{void upload(e.target.files?.[0],'photo');e.target.value=''}}/></label><div className="brand-canvas-wrap" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0],'photo')}}>{!photo?<div className="brand-empty"><strong>Tu imagen aparecerá aquí</strong><span>Selecciona una fotografía para comenzar.</span></div>:<canvas ref={canvasRef} aria-label="Imagen con logo y texto" onPointerDown={down} onPointerMove={move} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}/>}</div>{photo&&<p className="brand-hint">{photo.width} × {photo.height} px · Se conserva la resolución al descargar.</p>}<p className="brand-status" role="status">{status}</p></section>
 <aside className="brand-controls"><section className="brand-card"><h2>1. Elige tu logo</h2>{catalogLoading&&<p>Cargando galería…</p>}{catalogError&&<p role="alert" className="brand-error">{catalogError} <button onClick={()=>void refresh()}>Reintentar</button></p>}<div className="brand-logo-gallery">{resources.filter(r=>r.kind==='logo').map(r=><button key={r.id} className={logoId===r.id?'selected':''} aria-pressed={logoId===r.id} onClick={()=>void chooseLogo(r)}><img src={r.url} alt=""/><span>{r.name}</span></button>)}</div><label className="brand-upload secondary">Subir mi propio logo<input type="file" accept="image/png" onChange={e=>{void upload(e.target.files?.[0],'logo');e.target.value=''}}/></label><label className="brand-check"><input type="checkbox" checked={showLogo} onChange={e=>setShowLogo(e.target.checked)}/>Mostrar logo</label></section>
 <section className="brand-card"><h2>Segundo logotipo</h2>{!secondEnabled?<button className="brand-primary" onClick={()=>{setSecondEnabled(true);setTarget('logo2')}}>Añadir un logotipo más</button>:<><p className="brand-hint">Elige otro logo de la galería o súbelo desde tu dispositivo.</p><div className="brand-logo-gallery">{resources.filter(r=>r.kind==='logo').map(r=><button key={r.id} className={logo2Id===r.id?'selected':''} aria-pressed={logo2Id===r.id} onClick={()=>void chooseLogo(r,'logo2')}><img src={r.url} alt=""/><span>{r.name}</span></button>)}</div><label className="brand-upload secondary">Subir segundo logo<input type="file" accept="image/png" onChange={e=>{void upload(e.target.files?.[0],'logo2');e.target.value=''}}/></label><label className="brand-check"><input type="checkbox" checked={showLogo2} onChange={e=>setShowLogo2(e.target.checked)}/>Mostrar segundo logo</label><button onClick={()=>{++logo2Request.current;setSecondEnabled(false);setLogo2(null);setLogo2Id('');setShowLogo2(true);setTransforms(t=>({...t,logo2:initialLogo2}));if(target==='logo2')setTarget('logo')}}>Quitar segundo logo</button></>}</section>
 <section className="brand-card"><h2>2. Agrega texto</h2><label>Texto del logotipo<textarea rows={3} maxLength={240} value={text} placeholder="Nombre de tu grupo o frase" onChange={e=>{setText(e.target.value.split('\n').slice(0,6).join('\n'));setTarget('text')}}/></label><label>Tipografía<select value={fontId} onChange={e=>setFontId(e.target.value)}><option value="" disabled>Selecciona una tipografía</option>{resources.filter(r=>r.kind==='font').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{!catalogLoading&&!resources.some(r=>r.kind==='font')&&<p>No hay tipografías disponibles en la galería.</p>}{fontBusy&&<p role="status">Cargando tipografía…</p>}{fontError&&<p role="alert" className="brand-error">{fontError}</p>}<label>Color del texto<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label>{text&&<button onClick={()=>setText('')}>Quitar texto</button>}<p className="brand-hint">Hasta 6 líneas. El texto se añade sin fondo.</p>{fontId==='brand-ringbearer'&&<p className="brand-hint">Ringbearer: uso privado, no comercial. <a href="/marca/ringbearer-original.zip">Archivo original y condiciones</a>.</p>}</section>
 <section className="brand-card"><h2>3. Ajusta cada elemento</h2><div className="brand-actions"><button aria-pressed={target==='logo'} className={target==='logo'?'selected':''} onClick={()=>setTarget('logo')}>Logo 1</button>{secondEnabled&&<button aria-pressed={target==='logo2'} className={target==='logo2'?'selected':''} onClick={()=>setTarget('logo2')}>Logo 2</button>}<button aria-pressed={target==='text'} className={target==='text'?'selected':''} onClick={()=>setTarget('text')}>Texto</button></div><p className="brand-hint">Ajustando: {target==='logo'?'logo 1':target==='logo2'?'logo 2':'texto'}</p><div className="brand-positions">{positions.map((label,i)=><button key={label} aria-label={label} title={label} disabled={!photo} onClick={()=>quick(i)}><span style={{justifySelf:['start','center','end'][i%3],alignSelf:['start','center','end'][Math.floor(i/3)]}}>•</span></button>)}</div><label>Tamaño: {Math.round(t.size*100)}%<input type="range" min=".05" max="1" step=".01" value={t.size} onChange={e=>update({size:Number(e.target.value)})}/></label><label>Opacidad: {Math.round(t.opacity*100)}%<input type="range" min=".1" max="1" step=".01" value={t.opacity} onChange={e=>update({opacity:Number(e.target.value)})}/></label><label>Rotación: {t.rotation}°<input type="range" min="-180" max="180" step="1" value={t.rotation} onChange={e=>update({rotation:Number(e.target.value)})}/></label><button onClick={()=>update(target==='logo'?initialLogo:target==='logo2'?initialLogo2:initialText)}>Restablecer {target==='logo'?'logo 1':target==='logo2'?'logo 2':'texto'}</button></section>
 <section className="brand-card brand-export"><h2>4. Descarga tu imagen</h2><label>Formato<select value={format} onChange={e=>setFormat(e.target.value)}><option value="png">PNG</option><option value="jpeg">JPG</option><option value="webp">WebP</option></select></label>{format!=='png'&&<label>Calidad: {Math.round(quality*100)}%<input type="range" min=".55" max="1" step=".01" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label>}<button className="brand-primary" disabled={!photo||busy||fontBusy||!!text.trim()&&!family} onClick={()=>void exportImage()}>{busy?'Preparando…':'Descargar imagen'}</button><p className="brand-hint">Tu fotografía y texto se procesan en este dispositivo. Solo los recursos que agregue administración se guardan en la galería compartida.</p></section></aside></div></div></main>
}
