'use client';
import Link from 'next/link';
import { useEffect,useState,type FormEvent } from 'react';
import { brandJson,loadBrandFont,type BrandResource } from '../../lib/brand-client';
import '../../herramientas/marca-imagenes/editor.css';
function ResourcePreview({item}:{item:BrandResource}){
 const [family,setFamily]=useState('serif');const [error,setError]=useState(false);
 useEffect(()=>{let active=true;if(item.kind==='font')loadBrandFont(item).then(f=>{if(active)setFamily(f)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[item]);
 return item.kind==='logo'?<img className="brand-thumbnail" src={item.url} alt={item.name}/>:<div className="brand-thumbnail font-sample" style={{fontFamily:family}}>{error?'Vista previa no disponible':'Guerreros de la Luz'}</div>;
}
export default function BrandManager(){
 const [items,setItems]=useState<BrandResource[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [edit,setEdit]=useState<BrandResource|null>(null),[name,setName]=useState(''),[kind,setKind]=useState<'logo'|'font'>('logo'),[file,setFile]=useState<File|null>(null),[inputKey,setInputKey]=useState(0);
 const [target,setTarget]=useState<BrandResource|null>(null),[confirmation,setConfirmation]=useState('');
 async function refresh(){setLoading(true);try{const d=await fetch('/api/brand',{cache:'no-store'}).then(brandJson);setItems(d.resources);}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 function reset(){setEdit(null);setName('');setKind('logo');setFile(null);setInputKey(k=>k+1)}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const f=new FormData();f.set('name',name);f.set('kind',kind);if(edit){f.set('id',edit.id);f.set('revision',String(edit.revision))}if(file)f.set('file',file);await fetch('/api/brand',{method:'POST',body:f}).then(brandJson);reset();setNotice('Recurso guardado. Ya está disponible en el editor.');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(){if(!target)return;setBusy(true);setError('');try{await fetch('/api/brand',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:target.id,revision:target.revision,confirmation})}).then(brandJson);if(edit?.id===target.id)reset();setTarget(null);setNotice('Recurso eliminado de la galería.');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="brand-app"><header className="brand-header"><Link href="/administracion">← Administración</Link><Link href="/marca">Abrir editor</Link></header><div className="brand-container"><h1>Logos y tipografías</h1><p>Los recursos de esta galería están disponibles para todos los que usen el editor.</p>{error&&<p className="brand-error" role="alert">{error} <button onClick={()=>void refresh()} disabled={busy}>Actualizar galería</button></p>}{notice&&<p role="status">{notice}</p>}
 <div className="brand-admin-layout"><form className="brand-card" id="resource-form" onSubmit={save}><h2>{edit?'Editar recurso':'Agregar recurso'}</h2><fieldset disabled={busy}><label>Nombre<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Tipo<select disabled={!!edit} value={kind} onChange={e=>{setKind(e.target.value as 'logo'|'font');setFile(null);setInputKey(k=>k+1)}}><option value="logo">Logotipo PNG</option><option value="font">Tipografía</option></select></label><label>{edit?'Reemplazar archivo (opcional)':'Archivo'}<input key={inputKey} type="file" required={!edit} accept={kind==='logo'?'.png':'.ttf,.otf,.woff,.woff2'} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><p className="brand-hint">Máximo 10 MB. {kind==='logo'?'PNG sin fondo, con transparencia.':'TTF, OTF, WOFF o WOFF2; descomprime el ZIP antes de subirlo.'}</p><button className="brand-primary">{busy?'Guardando…':'Guardar recurso'}</button>{edit&&<button type="button" onClick={reset}>Cancelar edición</button>}</fieldset></form>
 <section aria-label="Galería de recursos">{loading&&<p role="status">Cargando galería…</p>}<div className="brand-resource-grid">{items.map(item=><article key={item.id} className="brand-card"><ResourcePreview item={item}/><h2>{item.name}</h2><p className="brand-hint">{item.kind==='logo'?'Logotipo PNG':'Tipografía'}</p><div className="brand-actions"><button disabled={busy} onClick={()=>{setEdit(item);setName(item.name);setKind(item.kind);setFile(null);setInputKey(k=>k+1);document.getElementById('resource-form')?.scrollIntoView({behavior:'smooth'})}}>Editar</button><button disabled={busy} onClick={()=>{setTarget(item);setConfirmation('')}}>Eliminar</button></div></article>)}</div>{!loading&&!items.length&&<p>La galería está vacía. Agrega el primer recurso.</p>}</section></div>
 <p className="brand-hint">Ringbearer: © Pete Klassen. Uso privado; no comercial ni modificaciones. <a href="/marca/ringbearer-original.zip">Paquete original y condiciones de uso</a>.</p>
 </div>{target&&<div className="brand-modal"><section className="brand-card" role="alertdialog" aria-modal="true" aria-labelledby="delete-resource"><h2 id="delete-resource">Eliminar {target.name}</h2><p>Dejará de estar disponible en la galería. Las imágenes ya descargadas se conservan.</p><label>Escribe «{target.name}» para confirmar<input autoFocus value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="brand-actions"><button disabled={busy} onClick={()=>setTarget(null)}>Cancelar</button><button disabled={busy||confirmation!==target.name} onClick={()=>void remove()}>{busy?'Eliminando…':'Eliminar recurso'}</button></div></section></div>}</main>
}
