import {shell} from './components/layout.js';import * as p from './pages/pages.js';import {groups} from './data/groups.js';import {centers} from './data/centers.js';import {experiences} from './data/experiences.js';import {openSites} from './services/sites.js';
const app=document.getElementById('app');
function cleanPath(){return location.pathname.replace(/\/+$/,'')||'/'}
function zoneName(slug){return ({jaguar:'Jaguar',tiburon:'Tiburón',delfin:'Delfín',colibri:'Colibrí',aguila:'Águila'})[slug]||''}
function render(){const path=cleanPath();let body;if(path==='/')body=p.home();else if(path==='/directorio')body=p.directory();else if(path.startsWith('/grupos/'))body=p.groupDetail(path.split('/')[2]);else if(path.startsWith('/zonas/'))body=p.directory(zoneName(path.split('/')[2]));else if(path==='/ayuda-adicciones-merida')body=p.help();else if(path==='/necesito-orientacion')body=p.orientation();else if(path==='/centros')body=p.centersPage();else if(path==='/experiencias'||path==='/escrituras')body=p.experiencesPage();else if(path==='/agenda')body=p.agendaPage();else if(path==='/universidad')body=p.university();else if(path==='/principios'||path==='/nosotros')body=p.principles();else if(path==='/noticias')body=p.news();else if(['/portal','/etica','/administracion','/administracion/universidad','/centros/acceso','/envios','/mensajeria'].includes(path))body=p.bridge(path==='/etica'?'Portal de Ética':path==='/envios'||path==='/mensajeria'?'Mensajería FGDLL':'Acceso FGDLL',path==='/mensajeria'?'/envios':path);else body=p.notFound();app.innerHTML=shell(body);wire();}
function wire(){document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.site-header nav')?.classList.toggle('open'));document.querySelectorAll('[data-link]').forEach(a=>a.addEventListener('click',e=>{const href=a.getAttribute('href');if(href?.startsWith('/')){e.preventDefault();history.pushState({},'',href);render();scrollTo(0,0)}}));document.querySelectorAll('[data-sites]').forEach(b=>b.addEventListener('click',()=>openSites(b.getAttribute('data-sites'))));wireGroups();wireCenters();wireExperiences();}
function wireGroups(){const grid=document.getElementById('groupGrid');if(!grid)return;const search=document.getElementById('groupSearch'),zf=document.getElementById('zoneFilter'),base=grid.dataset.zone||'';const draw=()=>{const q=(search.value||'').toLowerCase(),z=zf.value||base;const list=groups.filter(g=>(!z||g.zona===z)&&(!q||[g.nombre,g.ciudad,g.estado,g.direccion].join(' ').toLowerCase().includes(q)));document.getElementById('groupCount').textContent=`${list.length} grupos encontrados`;grid.innerHTML=list.map(g=>`<article class="card"><span class="badge">${g.id} · ${g.zona}</span><h3>${g.nombre}</h3><p>${g.ciudad||g.estado||'Ubicación por confirmar'}</p>${g.horarios?`<small>${g.horarios}</small>`:''}<div class="actions">${g.whatsapp?`<a class="btn small" target="_blank" href="https://wa.me/52${g.whatsapp}">WhatsApp</a>`:''}<a class="btn small" href="/grupos/${g.slug}" data-link>Ver grupo</a></div></article>`).join('');grid.querySelectorAll('[data-link]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();history.pushState({},'',a.getAttribute('href'));render();scrollTo(0,0)}));};search.addEventListener('input',draw);zf.addEventListener('change',draw);draw();}
function wireCenters(){const grid=document.getElementById('centerGrid');if(!grid)return;const s=document.getElementById('centerSearch');const draw=()=>{const q=(s.value||'').toLowerCase();const list=centers.filter(c=>!q||[c.nombre,c.familia,c.direccion,c.responsable].join(' ').toLowerCase().includes(q));grid.innerHTML=list.map(c=>`<article class="card"><span class="badge">${c.familia||'Centro independiente'}</span><h3>${c.nombre}</h3><p>${c.direccion}</p><small>Responsable: ${c.responsable||'por confirmar'}</small>${c.tel?`<div class="actions"><a class="btn small" target="_blank" href="https://wa.me/52${c.tel}">WhatsApp</a><a class="btn small" href="tel:+52${c.tel}">Llamar</a></div>`:''}</article>`).join('')};s.addEventListener('input',draw);draw();}
function wireExperiences(){const grid=document.getElementById('experienceGrid');if(!grid)return;const z=document.getElementById('expZone'),m=document.getElementById('expMonth'),months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];const draw=()=>{const list=experiences.filter(e=>(!z.value||e.zona===z.value)&&(!m.value||String(e.mes)===m.value));grid.innerHTML=list.map(e=>`<article class="card"><span class="badge">${months[e.mes]} · Zona ${e.zona}</span><h3>${e.tipo}</h3><p><b>${e.rango}</b></p><small>${[...e.salas,...e.temas].join(' · ')}</small></article>`).join('')};z.addEventListener('change',draw);m.addEventListener('change',draw);draw();}
addEventListener('popstate',render);render();
